# Generated by Django 5.0.6 on 2024-07-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0002_face'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
