# Generated by Django 5.0.6 on 2024-07-05 11:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0003_face_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='camerastream',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ddnscamera',
            name='name',
            field=models.CharField(default='DDNS Camera', max_length=255),
        ),
        migrations.AddField(
            model_name='staticcamera',
            name='name',
            field=models.CharField(default='Static Camera', max_length=255),
        ),
    ]
