# Generated by Django 5.0.6 on 2024-07-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0004_camerastream_created_at_ddnscamera_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='face',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='faces/'),
        ),
        migrations.AlterField(
            model_name='face',
            name='embedding',
            field=models.TextField(),
        ),
    ]
