# Generated by Django 5.0.6 on 2024-07-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0005_face_image_alter_face_embedding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='face',
            name='embedding',
            field=models.BinaryField(),
        ),
    ]
